{
 "title": "batch_metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(drift_detected) AS \"Batch predictions\" FROM drift_prediction WHERE drift_detected = false LIMIT 50 "
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tSUM(CAST(drift_detected AS INTEGER)) AS Drifts,\r\n\tCOUNT(*) AS \"Total batch preds\"\r\nFROM public.drift_prediction\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(drift_detected) AS \"Drifts\" FROM drift_prediction WHERE drift_detected = true LIMIT 50 "
    }
   ]
  },
  {
   "title": "Drift on batch predictions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT batch_date, drift_score FROM drift_prediction LIMIT 50 "
    }
   ]
  },
  {
   "title": "Drift detected on predictions",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT batch_date, drift_detected FROM drift_prediction LIMIT 50 "
    }
   ]
  },
  {
   "title": "Drift on dataset detected",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT batch_date, dataset_drift FROM drift_dataset LIMIT 50 "
    }
   ]
  },
  {
   "title": "Drift on dataset",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT batch_date, share_of_drifted_columns FROM drift_dataset LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of columns drifted",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT batch_date, number_of_drifted_columns FROM drift_dataset LIMIT 50 "
    }
   ]
  }
 ]
}