{
 "title": "training_metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Training metrics",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT rmse, mae, r2, error_std FROM metrics LIMIT 1 "
    }
   ]
  },
  {
   "title": "QQ Plot",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"Theorical Quantiles\",\r\n  \"Sample Quantiles\"\r\nFROM\r\n  qqdata"
    }
   ]
  },
  {
   "title": "Error distribution",
   "type": "histogram",
   "gridPos": { "h": 13, "w": 12, "x": 9, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT order_statistic_medians_y FROM order_statistic_medians_y ORDER BY order_statistic_medians_y DESC "
    }
   ]
  }
 ]
}