apiVersion: 1

datasources:
  - name: PostgreSQL_metrics_training
    type: postgres
    access: proxy
    url: database.:5432
    database: metrics_training
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: 'disable'
  - name: PostgreSQL_metrics_batch
    type: postgres
    access: proxy
    url: database.:5432
    database: metrics_batch
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: 'disable'
